# Generated by Django 4.0.5 on 2022-07-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='avatar1',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
