# Generated by Django 4.0.5 on 2022-07-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customusermodel_avatar1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='avatar1',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='okulno',
            field=models.IntegerField(default=1, max_length=6, unique=True),
        ),
    ]
