# Generated by Django 4.0.5 on 2022-07-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_customusermodel_avatar1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='okulno',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
