# Generated by Django 4.0.5 on 2022-07-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customusermodel_okulno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='okulno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
