# Generated by Django 4.0.5 on 2022-07-06 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customusermodel_okulno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='okulno',
        ),
    ]
