# Generated by Django 4.0.5 on 2022-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, unique=True)),
                ('last_name', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
