# Generated by Django 4.0.5 on 2022-07-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
